SELECT CITY.CITY_NAME, PRODUCT.PRODUCT_NAME , INVOICE_ITEM.LINE_TOTAL_PRICE FROM CITY, PRODUCT, CUSTOMER, INVOICE_ITEM, INVOICE 
WHERE CITY.ID = CUSTOMER.CITY_ID AND CUSTOMER.ID = INVOICE.CUSTOMER_ID AND INVOICE.ID = INVOICE_ITEM.INVOICE_ID AND INVOICE_ITEM.PRODUCT_ID = PRODUCT.ID
ORDER BY  INVOICE_ITEM.LINE_TOTAL_PRICE DESC, CITY.CITY_NAME ASC, PRODUCT.PRODUCT_NAME ASC
